import fs from "node:fs";
import path from "node:path";
import log from "electron-log/main";
import { E2E_TEST_DIR } from "../types/tests";
import { TEST_BASE_URL_ENV, TEST_RESULTS_JSON } from "./playwright_bootstrap";
import { PREVIEW_CDP_ENDPOINT_ENV } from "@/main/preview_debugging";

const logger = log.scope("playwright_preview_bootstrap");

/**
 * Directory (app-relative) holding everything the preview-panel run mode needs.
 * Kept out of the app root so the experiment adds exactly one visible entry,
 * and gitignored so it never lands in the user's commits.
 */
export const PREVIEW_RUNNER_DIR = ".dyad-e2e";

export const PREVIEW_CONFIG_PATH = `${PREVIEW_RUNNER_DIR}/playwright.config.ts`;

/**
 * Value for `PLAYWRIGHT_JSON_OUTPUT_NAME` in this mode.
 *
 * Playwright resolves reporter output paths (and `outputDir`) against the
 * CONFIG's directory, not the working directory. In the launch mode those are
 * the same place so the distinction never showed up; here the config lives in
 * `.dyad-e2e/`, so the plain value would put the report one level down and
 * every run would report "the test runner didn't produce a report".
 *
 * Stepping back out keeps every artifact — report, screenshots, traces — in the
 * app's own `test-results/`, exactly where the launch mode puts them. That
 * matters beyond tidiness: `readTestScreenshotDataUrl` only serves files whose
 * first path segment is `test-results`, so screenshots written anywhere else
 * are silently unavailable to the Tests panel and the agent.
 */
export const PREVIEW_JSON_OUTPUT_NAME = `../${TEST_RESULTS_JSON}`;
const PREVIEW_TSCONFIG_PATH = `${PREVIEW_RUNNER_DIR}/tsconfig.json`;
const PREVIEW_FIXTURE_PATH = `${PREVIEW_RUNNER_DIR}/fixture.ts`;

/**
 * The fixture that makes an unmodified spec run against the preview panel.
 *
 * Specs keep importing `@playwright/test`; the config's `tsconfig` (below)
 * rewrites that specifier to this file. It re-exports everything from
 * `playwright/test` — the same API under a different specifier, so this file
 * doesn't alias itself — and replaces only the `page` fixture with the
 * already-open preview view, reached over CDP.
 *
 * Nothing launches a browser, so no Chromium download and no extra window.
 */
export function buildPreviewFixture(): string {
  return `// Generated by Dyad. Do not edit — regenerated on every preview-panel test run.
//
// Redirects Playwright's \`page\` fixture at the app preview already open inside
// Dyad, instead of launching a browser. Specs are unchanged: the config's
// \`tsconfig\` maps "@playwright/test" to this file.
import { test as base, chromium, type Browser, type Page } from "playwright/test";

const CDP_ENDPOINT = process.env.${PREVIEW_CDP_ENDPOINT_ENV};
const BASE_URL = process.env.${TEST_BASE_URL_ENV};

function requireEnv(name: string, value: string | undefined): string {
  if (!value) {
    throw new Error(
      \`\${name} is not set. Preview-panel tests are launched by Dyad; run them from the Tests panel.\`,
    );
  }
  return value;
}

export const test = base.extend<{ page: Page }, { previewBrowser: Browser }>({
  // Worker-scoped: one CDP attach for the whole file rather than per test.
  previewBrowser: [
    async ({}, use) => {
      const browser = await chromium.connectOverCDP(
        requireEnv("${PREVIEW_CDP_ENDPOINT_ENV}", CDP_ENDPOINT),
      );
      await use(browser);
      // Detaches the CDP session. Dyad itself keeps running.
      await browser.close();
    },
    { scope: "worker" },
  ],

  page: async ({ previewBrowser }, use, testInfo) => {
    const baseUrl = requireEnv("${TEST_BASE_URL_ENV}", BASE_URL);
    const origin = new URL(baseUrl).origin;
    const context = previewBrowser.contexts()[0];
    if (!context) {
      throw new Error("Dyad's preview is not available over CDP.");
    }

    const page = context.pages().find((p) => p.url().startsWith(origin));
    if (!page) {
      throw new Error(
        \`No preview page is showing \${origin}. Open pages: \${context
          .pages()
          .map((p) => p.url())
          .join(", ")}\`,
      );
    }

    // A CDP-attached context carries no \`baseURL\` option, so Playwright can't
    // resolve a relative goto/waitForURL on its own. Resolve them here so
    // \`page.goto("/")\` keeps working exactly as it does in a launched browser.
    //
    // Guarded: this Page is the preview view, which outlives the test, so an
    // unguarded patch would wrap the previous test's wrapper on every test.
    const patchable = page as Page & { __dyadBaseUrlPatched?: boolean };
    if (!patchable.__dyadBaseUrlPatched) {
      patchable.__dyadBaseUrlPatched = true;
      const originalGoto = page.goto.bind(page);
      page.goto = ((url: string, options?: Parameters<typeof originalGoto>[1]) =>
        originalGoto(
          new URL(url, baseUrl).toString(),
          options,
        )) as typeof page.goto;
      const originalWaitForURL = page.waitForURL.bind(page);
      page.waitForURL = ((
        url: string | RegExp | ((url: URL) => boolean),
        options?: Parameters<typeof originalWaitForURL>[1],
      ) =>
        originalWaitForURL(
          typeof url === "string" ? new URL(url, baseUrl).toString() : url,
          options,
        )) as typeof page.waitForURL;
    }

    await use(page);

    // Capture the failure screenshot by hand. The config's
    // \`screenshot: "only-on-failure"\` would shoot EVERY page in the attached
    // context — and one of those is Dyad's own window, so the panel would show
    // (and the agent would upload) a picture of the user's chat and code
    // instead of the app. Attaching it as "screenshot" is what Dyad's report
    // parser looks for.
    if (testInfo.status !== testInfo.expectedStatus) {
      try {
        // Write to a file and attach by path, not by body: the JSON reporter
        // inlines a body as base64 and leaves \`path\` undefined, and Dyad's
        // report parser only picks up attachments that have a path.
        const file = testInfo.outputPath("test-failed-1.png");
        await page.screenshot({ path: file });
        await testInfo.attach("screenshot", {
          path: file,
          contentType: "image/png",
        });
      } catch {
        // A screenshot is a nice-to-have; never fail teardown over it.
      }
    }
  },
});

// Everything else (expect, devices, …) passes straight through; the explicit
// \`test\` above wins over this star export.
export * from "playwright/test";
`;
}

/**
 * Maps the `@playwright/test` specifier to the fixture for every file Playwright
 * loads under this config. This is what keeps user specs untouched.
 */
export function buildPreviewTsconfig(): string {
  return `{
  "//": "Generated by Dyad. Rewrites @playwright/test to the preview fixture.",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@playwright/test": ["./fixture.ts"]
    }
  }
}
`;
}

export function buildPreviewConfig(): string {
  return `import { defineConfig } from "@playwright/test";

// Generated by Dyad for the preview-panel test mode. Tests run against the app
// preview already open in Dyad (attached over CDP), so there is no browser to
// launch and no \`webServer\` to start.
export default defineConfig({
  testDir: "../${E2E_TEST_DIR}",
  // Redirects every spec's "@playwright/test" import at ./fixture.ts.
  tsconfig: "./tsconfig.json",
  // Paths here resolve against THIS file's directory, so the "../" keeps
  // screenshots, traces and the report in the app's own test-results/ — the
  // same place the normal (browser-launching) mode writes them.
  outputDir: "../test-results",
  // There is exactly one preview view, so runs are strictly serial. This mode
  // ignores the Tests panel's "parallel" option for that reason.
  workers: 1,
  fullyParallel: false,
  reporter: [["json", { outputFile: "../${TEST_RESULTS_JSON}" }]],
  use: {
    baseURL: process.env.${TEST_BASE_URL_ENV},
    // Both of these are context-wide, and the attached context also contains
    // Dyad's own window — so they would capture the user's chat and code, not
    // just the app. The fixture attaches a screenshot of the preview page
    // only; traces are unavailable in this mode for the same reason.
    screenshot: "off",
    trace: "off",
  },
});
`;
}

/**
 * Write (or refresh) the preview-mode runner files. Cheap and idempotent, so it
 * runs before every preview-mode test run — that also means an older generated
 * copy is always brought up to date.
 */
export function ensurePreviewRunnerFiles(appPath: string): void {
  const dir = path.join(appPath, PREVIEW_RUNNER_DIR);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(
    path.join(appPath, PREVIEW_CONFIG_PATH),
    buildPreviewConfig(),
  );
  fs.writeFileSync(
    path.join(appPath, PREVIEW_TSCONFIG_PATH),
    buildPreviewTsconfig(),
  );
  fs.writeFileSync(
    path.join(appPath, PREVIEW_FIXTURE_PATH),
    buildPreviewFixture(),
  );
  appendPreviewGitignoreEntry(appPath);
  logger.info(`Wrote preview-panel runner files to ${PREVIEW_RUNNER_DIR}/`);
}

function appendPreviewGitignoreEntry(appPath: string): void {
  const entry = `/${PREVIEW_RUNNER_DIR}/`;
  const gitignorePath = path.join(appPath, ".gitignore");
  let existing = "";
  if (fs.existsSync(gitignorePath)) {
    existing = fs.readFileSync(gitignorePath, "utf8");
  }
  const lines = new Set(existing.split(/\r?\n/).map((line) => line.trim()));
  if (lines.has(entry)) return;
  const prefix = existing.length > 0 && !existing.endsWith("\n") ? "\n" : "";
  fs.appendFileSync(gitignorePath, `${prefix}${entry}\n`);
}
